# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets  # dataset root dir
train: 
    - fire/train/images  # train images
    - VisDrone/VisDrone2019-DET-train/images
val: 
    - fire/val/images
    - VisDrone/VisDrone2019-DET-val/images
test:  # test images (optional)

names:
  0: pedestrian
  1: people
  2: bicycle
  3: car
  4: van
  5: truck
  6: tricycle
  7: awning-tricycle
  8: bus
  9: motor
  10: fire
  11: smoke